---
openapi: 3.0.0
info:
  title: This is just an example of User CRUD API
  version: 1.0.0
paths:
  /policies:
    get:
      summary: List all lifecycle policies
      responses:
        '200':
          description: List of policies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Policy'
    post:
      summary: Create a new lifecycle policy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        '201':
          description: Lifecycle policy created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
  /rules/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '404':
          description: User not found
    put:
      summary: Update a lifecycle policy by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '404':
          description: User not found
    delete:
      summary: Delete a lifecycle policy by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Lifecycle policy deleted
        '404':
          description: Lifecycle policy not found
components:
  schemas:
    Metadata:
      type: object
      description: Metadata about entity creation.
      properties:
        createdAt:
          type: string
          format: date-time
          description: The date and time when the entity was created.
      required:
        - createdAt
    Policy:
      type: object
      properties:
        id:
          description: The resource's unique identifier.
          type: string
          example: 15f67991-0f51-4efc-a8ad-ef1fb31a480c
          readOnly: true
        name:
          type: string
        prefix:
          type: string
        action:
          type: string
        time:
          type: string
          description: Number of days or ISO8601 duration
        metadata:
          type: object
          $ref: "#/components/schemas/Metadata"
      required:
        - name
        - prefix
        - action
        - time
