---
name: Build Image and Push to Registry

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'pkg/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'pkg/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Get token
        id: get_token_pr
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.IONOS_CLOUD_REPO_READ_APP_ID }}
          private_key: ${{ secrets.IONOS_CLOUD_REPO_READ_SECRET }}
          # needed for local testing with act
          github_api_url: https://api.github.com
      - id: image_tag
        name: "Generate Image Tag"
        run: |
          echo "image_tag=$(date +%Y%m%d).$(date +%H%M%S)-\
          ${GITHUB_RUN_ID}-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: "[Docker] Login to GitHub Packages Docker Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HARBOR_URL }}/rest-image
          username: ${{ vars.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      - name: "Build Image"
#        run: |
#          make docker-build -e \
#          TAG=${{ vars.HARBOR_URL }}:${{ steps.image_tag.outputs.image_tag }} \
#          VERSION=${{ steps.image_tag.outputs.image_tag }} \
#          GITHUB_TOKEN=${{ steps.get_token_pr.outputs.token }} \
#          GITHUB_USER="x-access-token"
      - name: Check if can be pushed
        id: check_push
        run: |
          echo "is_pushable=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; \
          then echo true;\
          else echo false;\
          fi)" >> "$GITHUB_OUTPUT"
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: ${{ steps.check_push.outputs.is_pushable }}
          context: .
          tags: |
            ${{ vars.HARBOR_URL }}:${{ steps.image_tag.outputs.image_tag }}
            ${{ vars.HARBOR_URL }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ steps.get_token_pr.outputs.token }}
#      - name: "Push Image to GitHub Packages Docker Registry"
#        if: github.ref == 'refs/heads/main'
#        run:
#          docker push ${{ vars.HARBOR_URL }}:${{ steps.image_tag.outputs.image_tag }} \
#      - name: "Push Image to GitHub Packages Docker Registry with latest tag"
#        if: github.ref == 'refs/heads/main'
#        run:
#          docker push ${{ vars.HARBOR_URL }}:latest \

      - name: "Deploy the new image"
        if: github.ref == 'refs/heads/main'
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: go-sample-service # you need to put your repo name here
          owner: ionos-cloud
          event_type: deploy
          message: |
            {
              "image_tag": "${{ steps.image_tag.outputs.image_tag }}"
            }
