---
name: Auto-Approve Renovate PRs
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approval
        uses: ionos-cloud/paas-github-actions/github/auto-approve@0.3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          users: |
            ionos-cloud-paas-bot
          labels: |
            ðŸ”¨renovate
